### ISSUE TITLE
iframe option: 1 AGS, two indicator, no UI

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#126]
![Bildschirmfoto 2022-09-15 um 15 49 55](https://user-images.githubusercontent.com/73465311/190421237-1af94781-c1b0-49b0-885f-524f71170496.png)

**Comment by more-ginger** [comment]
Don't understand the bug

**Comment by johannahaha** [comment]
at one point we discussed if we want to allow editors to set 1 LK with 2 sections, so e.g. Mobility & Energy of Berlin, but nothing else

**Comment by more-ginger** [comment]
I think right now we won't add any new variable for editors, maybe we can keep it in mind if they ask for it?
