### ISSUE TITLE
dropdown arrow "v" not clickable in LK view

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#157]
in LK view you cannot open the dropdown to add other Landkreises with the arrow, only by clicking on the field with the current LK
![Bildschirmfoto 2022-09-20 um 10 52 45](https://user-images.githubusercontent.com/73465311/191213787-4b0b698c-7d4b-4204-922d-c64d0a4e431a.png)

**Comment by more-ginger** [comment]
it was a problem with boxes, it's currently fixed on `building-vis` branch
