### ISSUE TITLE
Postcard texts do not contain linebreaks as in csv (does it need to be coded differently? <br> instead of \n?)

### ISSUE THREAD

**Issue by LalonSander** [uclab-potsdam/klimataz#169]
![Bildschirmfoto_2022-09-20_14-58-50](https://user-images.githubusercontent.com/96609092/191264445-a96eb2cc-6dec-4571-b03f-883976031177.png)

**Comment by johannahaha** [comment]
note for later:
https://stackoverflow.com/questions/50229792/adding-a-new-line-in-a-jsx-string-inside-a-paragraph-react

**Comment by johannahaha** [comment]
<img width="894" alt="Bildschirmfoto 2022-09-21 um 15 26 42" src="https://user-images.githubusercontent.com/73465311/191516253-3af075b5-81f0-454a-82d9-66ce503344c4.png">
is this correct?

**Comment by LalonSander** [comment]
Almost. The first paragraph has two linebreaks after "Berlin." and "sein." that shouldn't be there.

If it helps, we could take out the empty lines between paragraphs.

**Comment by johannahaha** [comment]
closed by #200
