### ISSUE TITLE
labels for energy source out of frame

### ISSUE THREAD

**Issue by aeschi** [uclab-potsdam/klimataz#194]
<img width="194" alt="Screenshot 2022-09-22 at 18 32 56" src="https://user-images.githubusercontent.com/56318362/191802744-56d0d0f3-f65b-48c7-9460-5b63fd26fbe3.png">

this was Bonn for example

**Comment by aeschi** [comment]
also this

![Image](https://user-images.githubusercontent.com/56318362/192251710-cf2870fd-303e-426e-be91-9b1e480539dd.png)

**Comment by johannahaha** [comment]
closed by #205
