### ISSUE TITLE
rating needs to be slightly changed in wording

### ISSUE THREAD

**Issue by aeschi** [uclab-potsdam/klimataz#219]

**Comment by aeschi** [comment]
so that it's "im oberen Drittel" or "oberes Drittel"

![Image](https://user-images.githubusercontent.com/56318362/192317656-e8c78864-e725-46b9-9f96-6f8fd1e9f734.png)

**Comment by johannahaha** [comment]
or am I wrong?

**Comment by johannahaha** [comment]
I am wrong :D
