### ISSUE TITLE
layout of comparison view

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#221]
- [x] scale up cards if there are two cards in comparison view for desktop
- [x] allow five cards to be selected
- [x] allow five LKs for iframe
- [x] new design of dropdown menu
- [x] hide selection in mobile dropdown for more than two LK
- [x] resizing of charts does not work when second LK is added

![Bildschirmfoto 2022-09-26 um 17 48 08](https://user-images.githubusercontent.com/73465311/192322387-c836081e-be63-472a-9324-53a93d2b82ef.png)

**Comment by more-ginger** [comment]
bring up to five number of currently comparable cards
