### ISSUE TITLE
chart updates for "tablet" sizes

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#226]
- [x] Ge consumption: positioning of year scale
- [x] Mo car density: positioning of label of electrical cars
- [x] in general: for long LK names it overlaps with the toggle labels

(screenshots are on the current iPad size)

<img width="718" alt="Bildschirmfoto 2022-09-27 um 15 26 42" src="https://user-images.githubusercontent.com/73465311/192539132-9503a68d-8767-49d7-8e97-d637f31fc308.png">
<img width="776" alt="Bildschirmfoto 2022-09-27 um 15 27 18" src="https://user-images.githubusercontent.com/73465311/192539258-aa46520a-bfe8-4ab3-936d-3aa90d19fbfa.png">

<img width="756" alt="Bildschirmfoto 2022-09-27 um 15 28 43" src="https://user-images.githubusercontent.com/73465311/192539608-d9e35aae-3fe6-4eb1-87dc-a9fcc69f64d2.png">

**Comment by more-ginger** [comment]
On tablet we can also have the toggle with generic label, hence the css can be copied from responsive.scss lines 233:249
