### ISSUE TITLE
backside css problems

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#230]
- [x] list is not clickable in chrome (first image)
- [x] no scrolling with the touchpad in firefox, only when using the small scroll bar
- [ ] again it is very slow for some of us

<img width="833" alt="Screenshot 2022-09-27 at 15 25 01" src="https://user-images.githubusercontent.com/73465311/192540524-33def345-048c-4888-99c7-825d0aaf439e.png">

**Comment by more-ginger** [comment]
Personally not having speed issue on back side re-render. @johannahaha can you confirm it's fixed?
