### ISSUE TITLE
swipe trigger comes too quick on mobile

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#248]
when looking and clicking around the labels on the energy postcard, sometimes the click is recognized as a swipe and the next postcard opens

we could either 
- add a distance measurement or something to the drag trigger
- highlight the names of the places more in the mobile version

**Comment by aeschi** [comment]
it doesn't happen so much on my phone in safari

**Comment by johannahaha** [comment]
then maybe we can also leave that up to the testers?

**Comment by aeschi** [comment]
sounds good
