### ISSUE TITLE
increase consistency of buttons and labels

### ISSUE THREAD

**Issue by nrchtct** [uclab-potsdam/klimataz#268]
The font sizes, styles and behaviors of buttons and their tooltips vary considerably. The cards would be a bit less busy, if they had a bit more consistency. Quick observations:

- share: currently no tooltip → add a similar tooltip as for Umdrehen! 
- share and turn icons have different sizes → use similar size, increase size of share button
- info: currently the label is shown, with very different font/weight than Umdrehen! tooltip → consider removing the label and use similar tooltip as for the other(s)
- toggle might benefit from a small tooltip underneath as the Umdrehen tooltip
- on hover the share and info buttons/icons change their color (differently so though), but toggle and turn do not → make on-hover color change consistent and add something like it to toggle and turn icons
- next card: yet another font size :)

<img width="149" alt="image" src="https://user-images.githubusercontent.com/578924/193200294-4c9cc175-6de3-4cfe-a47e-748453f3a292.png">
<img width="87" alt="image" src="https://user-images.githubusercontent.com/578924/193200315-35032863-a522-4b7d-80b4-35de1e4bf296.png">
<img width="180" alt="image" src="https://user-images.githubusercontent.com/578924/193200337-b813884b-19c8-46c8-9db5-8711a0358f1c.png">
<img width="79" alt="image" src="https://user-images.githubusercontent.com/578924/193201048-2f16ec49-ce9c-4980-b3fb-85aae5273deb.png">
<img width="64" alt="image" src="https://user-images.githubusercontent.com/578924/193201260-d116c4f9-446b-4b0f-8e03-8c16f7fa0317.png">

**Comment by more-ginger** [comment]
- [ ] share: currently no tooltip → add a similar tooltip as for Umdrehen!
- [ ] share and turn icons have different sizes → use similar size, increase size of share button
- [ ] info: currently the label is shown, with very different font/weight than Umdrehen! tooltip → consider removing the label and use similar tooltip as for the other(s)
- [ ] on hover the share and info buttons/icons change their color (differently so though), but toggle and turn do not → make on-hover color change consistent and add something like it to toggle and turn icons
