### ISSUE TITLE
heating chart bugs in mobile safari

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#271]
- [x] overlapping flip button with text
 - [x] text outside of card on energy primary (footnote issue)
 - [ ] building heating top of vis cut of
 - [ ] also unit covered by years

#28

**Comment by johannahaha** [comment]
![193063874-2b306ad0-966d-4b6b-97d7-eef7c16e09bd](https://user-images.githubusercontent.com/73465311/193216792-3997914c-568f-4446-bfd6-7e624012e019.PNG)

**Comment by johannahaha** [comment]
<img width="355" alt="Bildschirmfoto 2022-09-30 um 10 42 31" src="https://user-images.githubusercontent.com/73465311/193234770-e48ce6d5-1e87-4d7f-b0fa-d5a60e5f79c9.png">
even more on smaller phones

**Comment by more-ginger** [comment]
labels overlapping too edge case to fix it now, maybe re-open later
