### ISSUE TITLE
mobile view daten wechseln cut off and too close to toggle

### ISSUE THREAD

**Issue by aeschi** [uclab-potsdam/klimataz#286]
<img width="417" alt="Screenshot 2022-09-30 at 15 32 07" src="https://user-images.githubusercontent.com/56318362/193281182-efbecc63-ffe8-45a8-88d2-1d30818189dd.png">

**Comment by johannahaha** [comment]
download button is gone in desktop
<img width="815" alt="Bildschirmfoto 2022-09-30 um 16 15 25" src="https://user-images.githubusercontent.com/73465311/193289518-a26b8335-95a0-4232-bcc4-267c6a90f7c4.png">
