### ISSUE TITLE
blank rectangle on second slide

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#295]
do we even need the "wie werden die indikatoren berechnet" if we have the info button?
<img width="970" alt="Bildschirmfoto 2022-10-04 um 09 16 55" src="https://user-images.githubusercontent.com/73465311/193758033-9626470b-7162-45ac-a3ec-98c14ad9064c.png">

**Comment by more-ginger** [comment]
you have a point, i'll just get rid of it across all versions
