### ISSUE TITLE
title of "Fahrer" in modal split

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#310]
title unclear at first
Fahrer --> Autofahrer or Autofahrer:in or PkW-Fahrer
Mitfahrer --> Automitfahrer or Automitfahrer:in

<img width="236" alt="Bildschirmfoto 2022-10-04 um 16 44 48" src="https://user-images.githubusercontent.com/73465311/193850495-56a5f25c-9a22-4da9-99a0-962fbc6f335a.png">

**Comment by more-ginger** [comment]
also icons need to be added, maybe this helps?

**Comment by johannahaha** [comment]
feedback:
i find the labels a bit weird in the transportmittel chart, i don’t think that ÖPV is a thing, and how is mitfahrer/fahrer a transportmittel?
--> maybe change toggle label of "transportmittel" to Arbeitswege?

**Comment by johannahaha** [comment]
Marians suggestions:
The description below does not match the car driver/passenger wording…  I would suggest this change:

Mitfahrer → Auto (Mitfahrer*in)
Fahrer → Auto (Fahrer*in)
