### ISSUE TITLE
reduce app/file size and clean up

### ISSUE THREAD

**Issue by aeschi** [uclab-potsdam/klimataz#312]
- [ ] deleting unnecessary images/svgs
- [ ] taking out unused snippets of code
- [ ] any unused libraries?
- [ ] check biggest files

**Comment by johannahaha** [comment]
also: each side is rendered twice because of the flipping logic

**Comment by johannahaha** [comment]
- check warnings of react

**Comment by johannahaha** [comment]
I checked all warnings, these are the ones that I left
<img width="1196" alt="Bildschirmfoto 2022-11-15 um 18 22 52" src="https://user-images.githubusercontent.com/73465311/201985417-3779e26a-3d8b-4adf-bf6a-5c7a29d253b6.png">

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint] 
src/components/Canvas.js
  Line 32:6:  React Hook useEffect has a missing dependency: 'getCheckedEditorsPick'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

src/components/Card.js
  Line 16:6:  React Hook useEffect has a missing dependency: 'flipped'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

src/components/LayoutManager.js
  Line 356:48:  Function declared in a loop contains unsafe references to variable(s) 'randomLK'  no-loop-func
  Line 361:46:  Function declared in a loop contains unsafe references to variable(s) 'randomLK'  no-loop-func

src/components/side-elements/vis/EnIndustry.js
  Line 266:28:  Array.prototype.map() expects a return value from function  array-callback-return

src/components/side-elements/vis/EnPrimaryEnergy.js
  Line 319:28:  Array.prototype.map() expects a return value from function  array-callback-return

src/components/side-elements/vis/LaAnimalCount.js
  Line 38:3:  Array prototype is read only, properties should not be added  no-extend-native

src/components/side-elements/vis/LaAnimalDensity.js
  Line 46:73:  Unexpected use of comma operator  no-sequences

webpack compiled with 1 warning
