### ISSUE TITLE
energy: add y axis

### ISSUE THREAD

**Issue by aeschi** [uclab-potsdam/klimataz#317]
- Hier würde ich auch noch die Einheiten für die Ordinate angeben (solved with adding default view of last value column similar to the source of energy - so not only on hover)
- und alles auch wirklich am Nullpunkt beginnen lassen und nicht irgendwo mittendrinen. (I don't think we want this)

<img width="884" alt="Screenshot 2022-10-04 at 17 06 27" src="https://user-images.githubusercontent.com/56318362/193855856-ef8a3edb-148b-42e9-bad7-ca2473f3be5d.png">

**Comment by johannahaha** [comment]
#331 
actually I got the same feedback for the "beginning at zero"

**Comment by aeschi** [comment]
add y-Axis
