### ISSUE TITLE
format of number: no decimals for thousands

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#324]
maybe it is easier to read if we skip the decimal when rounding to thousands

114,2 Tsd TJ => 114 Tsd TJ

**Comment by aeschi** [comment]
good point but when its 1,4 Tsd it's a big difference to just 1 Tsd

**Comment by johannahaha** [comment]
I had another issue about the 1 Tsd. numbers, I will close it so we can talk about it here. My idea was to keep the normal number if the number is below 9999. Because 1,1 Tsd. is a maybe harder to read?
1,4 Tsd => 1410
10,6 Tsd => 11 Tsd

<img width="553" alt="Bildschirmfoto 2022-10-05 um 10 27 58" src="https://user-images.githubusercontent.com/73465311/194015961-b5023e7a-12da-4129-b290-eda67feb369f.png">
