### ISSUE TITLE
modal split: label of "trip counts"

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#329]
trip count not interpreted correctly
- I though this is Km again, but this time with percentages
- not understood what it means and how it is different from vis on the left

<img width="139" alt="Bildschirmfoto 2022-10-04 um 18 23 06" src="https://user-images.githubusercontent.com/73465311/193873072-776d80a8-2677-483c-a58c-1741442346e9.png">

**Comment by more-ginger** [comment]
Work on labels and text
