### ISSUE TITLE
agriculture animal count: legend misinterpreted

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#330]
See feedback in the google docs
maybe
- add beige color to the legend
- rename "im Vergleich zu" --> "Anzahl aus vorheriger Zählung"

**Comment by more-ginger** [comment]
- [ ] no legend, but axis that says "benchmark" on 2010
- [ ] use arrows to make clear the relationship between dotted and new half circle
- [ ] Make 2010 border dotted as in other years
- [ ] Remove the dotted circle from legend

**Comment by johannahaha** [comment]
#397 --> treat nan differently than zero

**Comment by johannahaha** [comment]
another feedback from tester:
Ich würde „Großvieheinheit“ bei „Anzahl in GV“ nochmal ausschreiben. Nicht alle lesen unbedingt (und schon gar nicht als erstes) den Begleittextext
