### ISSUE TITLE
energy stream graph misinterpreted

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#331]
the horizontal alignment of the stream graph not understandable

See details in the google docs.

maybe move axis / 0 zero to the bottom?

**Comment by more-ginger** [comment]
Discuss with @aeschi if it should start from 0

**Comment by aeschi** [comment]
<img width="1464" alt="Screenshot 2022-10-11 at 10 14 25" src="https://user-images.githubusercontent.com/56318362/195035860-b6638f79-2301-4ba9-af9c-981afe3ce389.png">
