### ISSUE TITLE
indicate change between LK and BL level data more

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#337]
change between Landkreis and Bundesland data is not apparent / is not recognized. we could add a sentence about the to the description of the chart?

feedback:
why is this data from Niedersachsen? I only see now, that the data is from Niedersachsen? I talked about the data as it would be from the Landkreis
for some charts, he did not even notice the change of the level

**Comment by johannahaha** [comment]
it could also help to highlight the name of the LK / BL more in the description?
(connected to Mark-Jans feedback)

<img width="702" alt="Bildschirmfoto 2022-10-04 um 16 19 54 (1)" src="https://user-images.githubusercontent.com/73465311/194492978-b262eec2-7462-4840-8ac5-97ca051c0279.png">

**Comment by aeschi** [comment]
also data in top bar is now bold
