### ISSUE TITLE
more clear indication of the switch to comparison view

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#345]
I don't know how to solve other than making it visually more different. Also we can wait and see if other testers said the same.

feedback:
- why do I only see the energy postcard now? all the other topics are gone
- “now the “sonnige grüße” is gone”
- but understood after some time, but was weird

**Comment by johannahaha** [comment]
other feedback: Dropdown is easy to use, but not clear as potential first interaction. User went directly in explore mode and overlooked the possibility to compare up to several minutes within the prototype.

**Comment by aeschi** [comment]
too generic issue
