### ISSUE TITLE
make toggle labels clickable

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#346]
the label of the toggle could also get a pointer cursor
(and be clickable)

![Bildschirmfoto 2022-10-05 um 11 41 58](https://user-images.githubusercontent.com/73465311/194030992-1d35618b-c6ad-45f9-b6e9-f53fb10ae65c.png)

**Comment by johannahaha** [comment]
started in branch "clickable-toggle-labels", but took more time than expected and does not work yet, so I stopped

**Comment by aeschi** [comment]
fix with #415
