### ISSUE TITLE
if city and LK have same name add (LK) to the name 

### ISSUE THREAD

**Issue by aeschi** [uclab-potsdam/klimataz#357]
It's not clear which one is the LK or Bundesland or city

<img width="958" alt="Screenshot 2022-10-07 at 09 11 54" src="https://user-images.githubusercontent.com/56318362/194492063-778d50a3-1c5d-4008-84ff-9855d1e8742f.png">

**Comment by johannahaha** [comment]
we have two different ways of dealing with this:
dropdown:
Augsburg (kreisfreie Stadt) vs Augsburg (Landkreis)
text on the backside:
Augsburg vs. Landkreis Augsburg
Maybe we can use the second version for the headline? I think the first version makes sense for the dropdown for the alphabetical order
