### ISSUE TITLE
Animal count shows zeroes instead of (what is presumably) no data

### ISSUE THREAD

**Issue by LalonSander** [uclab-potsdam/klimataz#397]
Maybe only a problem for Münster?

![Bildschirmfoto_2022-10-12_15-42-56](https://user-images.githubusercontent.com/96609092/195359002-ca317426-1d25-401c-b448-c9df9dfc9e61.png)

**Comment by johannahaha** [comment]
I just checked, apparently in the data for Münster, the values for 2016 are Nan (so unknown), not Zero. We should add that to the vis.
<img width="244" alt="Bildschirmfoto 2022-10-13 um 09 08 58" src="https://user-images.githubusercontent.com/73465311/195526444-16253d32-2773-4995-8a59-70e54e0a7555.png">

**Comment by aeschi** [comment]
sollen wir in dem Fall "keine Angabe", "k.A.", "n. a.", "N/A" oder "unbekannt" schreiben? @LalonSander

**Comment by LalonSander** [comment]
Was Null in den Daten ist, war "." in der Tabelle. Aus der Zeichenerklärung: ". -> Zahlenwert unbekannt oder geheimzuhalten"

dH besser "Unbekannt/Geheim"

**Comment by aeschi** [comment]
ist allerdings etwas lange... wir könnten auch n.a. oder etwas anderes kurzes Angeben und unter Quellen schreiben, dass es Unbekannt/Geheim entspricht?

<img width="700" alt="Screenshot 2022-10-17 at 14 32 08" src="https://user-images.githubusercontent.com/56318362/196177759-d349a0a1-d224-4999-ad04-ecf312bf7d33.png">

**Comment by LalonSander** [comment]
Dann ist "Unbekannt" besser als "Geheim". Ich glaube, ich würde das Label schon lieber auf der Grafik direkt haben
