### ISSUE TITLE
make selected toggle labels bold

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#415]
is the toggle the right element for switching the graphic? Does it need to be tabs?

Ich frage mich, ob der Schiebeschalter das richtige Element ist, um zu switschen. Irgendwie erwarte ich da eher eine andere Ansicht der gleichen Daten und nicht eine ganz andere Grafik. Tabs oder Reiter scheinen mir da eigentlich das sinnigere Bedienelement

**Comment by aeschi** [comment]
instead making the selected data bold
