### ISSUE TITLE
show dropdown in postcard view

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#417]
drowdown should be visible in postcard view, so I can easily search for places even if I am looking at the postcard. Otherwise the search can be overlooked

(feedback from multiple testers)

**Comment by aeschi** [comment]
we leave the dropdown from tablet screen size. So only sizes where the region title also stays on top in postcardview

<img width="825" alt="Screenshot 2022-10-24 at 17 00 10" src="https://user-images.githubusercontent.com/56318362/197558720-35545c87-0603-4802-9199-d59315c38591.png">

**Comment by aeschi** [comment]
see also  #496
