### ISSUE TITLE
helpbox: change "man" to "du"

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#419]
In dem Text „Wie bediene ich die Postkarten“ würde ich mit „du“ statt „man“ Antworten – oder die Frage ändern. Also „In der  Suchleiste  kannst du nach einem beliebigen Landkreis oder Bundesland suchen.

**Comment by aeschi** [comment]
#close419 bc it already is " In der Suchleistekann nach einem beliebigen Landkreis oder Bundesland gesucht werden."
