### ISSUE TITLE
possibility to select "non-similar" location

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#420]
I think, this is too much work. Now that the zoom view of the locator map is clickable, you can also got to  locations with a different ranking

feedback:
Es wäre schön, wenn man irgendwie eine Stadt im besten Drittel auswählen könnte, wenn man gerade eine (zufällige?) Karte aus dem schlechtesten Drittel auswählen könnte. Oder finde ich das nur nicht?

**Comment by aeschi** [comment]
I also think it's unnecessary & now you can click on surrounding places with a worse rating, so it should be fine
