### ISSUE TITLE
consistency of front/back side when going to next card

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#423]
there seems to be a bit of inconsistency with the front & back side when going back and forth between cards.

feedback:
der detailgrad wie ihr das an das verhalten an echte postkaten angenähert hat, beeindruckt mich. se bleiben sogar umgedreht, wenn ich den stapel durchgehe und wieder an der stelle bin, sehe ich weiterhin die rückseite
ich finds toll, aber vll auch verwirrend, dass es nicht immer vor- oder rückseite ist
und das ist natürlich ein tolles tool um rumzuspielen, aber bei den ganzen infos braucht ihr, das hast du sicher auf dem schirm, noch eine alternative, wo die leser*in durchgeführt wird. eher als longread mit den einzelnen karten, wo nan auf bestimmteerkenntnisse hinweisen kann

**Comment by more-ginger** [comment]
I am not sure I get the feedback, could you explain the comment to me?

**Comment by aeschi** [comment]
they love the postcards
they think it can be confusing when you swipe through cards and one is turned to the back that the others are on the front. 


we discussed this multiple times. I think it makes more sense this way.
I would close bc irrelevant.
