### ISSUE TITLE
export front and backside when downloading card

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#424]
this is probably to complicated to do I think, right?

Feedback:
und vielleicht schade, dass man eben nicht die ganze postkarte beim download bekommt. sondern nur die vorder ODER rückseite, die man sich gerade ansieht
- wenn man die postkarten mobil runterläd sind sie natürlich hochformat, nicht so richtig postkartenstyle, aber kann man schon machen
- ich frag mich nur, ob man das "sonnige grüße aus berlin" nicht noch irgendwie besser erklären muss. weil wenn mir jemand so eine postkarte shcicke, hab ich ja keinen anderen kontext
zeigt doch mal leuten, die nichst über das projekt wissen, ob sie die heruntergeladene postkarte verstehen also vor allem, wenn man nur die vorderseite seiht ohne text
also man sollte eh beides zusammen runterladen denke ich. vorder und rückseite

--> See #410 for quick fix & compromise maybe

**Comment by aeschi** [comment]
I think it makes sense to only download the shown image (front or back side not both)
