### ISSUE TITLE
Landkreis Harburg

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#487]
This is a really small detail, but my hometown Landkreis Harburg should not be only "Harburg" but "Landkreis Harburg". Harburg is a district of Hamburg and the historic "kreisfreie Stadt" of the Landkreis. So just saying "Harburg" on the postcard is kind of wrong, because it makes you think you are talking about the district of hamburg.
I don't know if there are any more cases like this

**Comment by aeschi** [comment]
nur anpassen falls es nicht zu lange dauert

**Comment by aeschi** [comment]
nur Anpassungen für Rückseite
