### ISSUE TITLE
the searchbar width can take up half of the width and the region title can be scaled down a bit more for the responsive sizes

### ISSUE THREAD

**Issue by aeschi** [uclab-potsdam/klimataz#496]
<img width="657" alt="Screenshot 2022-10-24 at 17 02 20" src="https://user-images.githubusercontent.com/56318362/197559248-d64c830d-7018-4d01-98c5-4cd0111463b0.png">

**Comment by more-ginger** [comment]
Think I solved this via #555 by pushing down the title, won't go further with edits
