### ISSUE TITLE
cannot open erneuerbare energies value labels in safari

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#527]
all Labels are showed when hovering, except for renewables energies.

primary energy chart, safari

https://user-images.githubusercontent.com/73465311/199502959-d4752622-f250-4a34-89cc-442d958e0ede.mov

**Comment by more-ginger** [comment]
This is connected to the top left label bug, I tried several solutions but I don't manage to solve it in any way. I gave up after a while :/
