### ISSUE TITLE
remove white background of modal split kilometers

### ISSUE THREAD

**Issue by johannahaha** [uclab-potsdam/klimataz#529]
there is always an odd white background of the kilometer labels.
sometimes it is even overlapping with the kilometer line.

<img width="726" alt="Bildschirmfoto 2022-11-02 um 14 37 32" src="https://user-images.githubusercontent.com/73465311/199503828-c191ae61-e70b-45bd-b1a5-54f2cdbe70ab.png">

<img width="70" alt="Bildschirmfoto 2022-11-02 um 14 38 02" src="https://user-images.githubusercontent.com/73465311/199503929-54dc7c47-6ae6-465e-a969-19ce89a652e9.png">

<img width="68" alt="Bildschirmfoto 2022-11-02 um 14 38 26" src="https://user-images.githubusercontent.com/73465311/199504020-bf357cad-bd3c-445f-9e7e-252c63e797c0.png">

<img width="76" alt="Bildschirmfoto 2022-11-02 um 14 38 49" src="https://user-images.githubusercontent.com/73465311/199504054-c4b0b5ca-b854-4988-a085-fd48a86bb5e4.png">

**Comment by more-ginger** [comment]
It's not a bug! Maybe I can change to something closer to the color?

**Comment by aeschi** [comment]
yes sounds good!

**Comment by aeschi** [comment]
but is the white part also part of the data or does it stop before the label. this was unclear to me

**Comment by johannahaha** [comment]
I think sometimes it is part of the data and sometimes not, if you look at the kilometers
foot, bike, mitfahrer: not part of the data
öpv, Fahrer: part of the data

**Comment by johannahaha** [comment]
and: looking at e.g. Bavaria and very large phones, one label is outside of the card
<img width="429" alt="Bildschirmfoto 2022-11-02 um 16 28 37" src="https://user-images.githubusercontent.com/73465311/199531232-d20e4ad3-718e-42ed-a179-66b0b264d7b5.png">
