### ISSUE TITLE
locator map jumping from mini tablet view or lower

### ISSUE THREAD

**Issue by aeschi** [uclab-potsdam/klimataz#538]
see video 
https://user-images.githubusercontent.com/56318362/199532988-6e43ca98-d4f5-433b-a0fb-c2d3b5c15c45.mov

**Comment by johannahaha** [comment]
I cannot see the video and don't know if that is already the issue, but in shortread, the locator map overlaps with the social media download
![Uploading Bildschirmfoto 2022-11-03 um 13.27.45.png…]()
